import pygame.key

SOLDIER_HEIGHT = 4
SOLDIER_WIDTH = 2
START_SOLDIER = (0, 0)
SCREEN_HEIGHT = 25
SCREEN_WIDTH = 50
FLAG_HEIGHT = 4
FLAG_WIDTH = 2
FLAG_X_Y = (25,50)
X_FLAG_MAX = SCREEN_WIDTH-FLAG_WIDTH
Y_FLAG_MAX = SCREEN_HEIGHT-FLAG_HEIGHT
MINES_HEIGHT = 1
MINES_WIDTH = 3
BACKGROUND_COLOR = (0, 100, 0)
NIGHT_COLOR = (0,0,0)
UP_KEY = pygame.K_UP
DOWN_KEY = pygame.K_DOWN
LEFT_KEY = pygame.K_LEFT
RIGHT_KEY = pygame.K_RIGHT
ENTER=pygame.K_KP_ENTER

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * SCREEN_WIDTH)
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE