import pygame.key

SOLDIER_HEIGHT = 4
SOLDIER_WIDTH = 2
START_SOLDIER = (0, 0)
SCREEN_HEIGHT = 24
SCREEN_WIDTH = 49
FLAG_HEIGHT = 4
FLAG_WIDTH = 2
FLAG_X_Y = (46, 21)
X_FLAG_MAX = 46
Y_FLAG_MAX = 21
MINES_HEIGHT = 1
MINES_WIDTH = 3
BACKGROUND_COLOR = (0, 100, 0)
NIGHT_COLOR = (0, 0, 0)
UP_KEY = pygame.K_UP
DOWN_KEY = pygame.K_DOWN
LEFT_KEY = pygame.K_LEFT
RIGHT_KEY = pygame.K_RIGHT
ENTER = pygame.K_KP_ENTER

BLACK = (0, 0, 0)
FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * SCREEN_WIDTH * 20)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * SCREEN_WIDTH * 20, SCREEN_HEIGHT * 20 / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = BLACK
WIN_LOCATION = \
    (0.2 * SCREEN_WIDTH * 20, SCREEN_HEIGHT * 20 / 2 - (WIN_FONT_SIZE / 2))

START_LOCATION = \
    (40, 20)
START_FONT_SIZE = int(0.15 * SCREEN_WIDTH*5)

ONE_KEY = pygame.K_1
TWO_KEY = pygame.K_2
THREE_KEY = pygame.K_3
FOUR_KEY = pygame.K_4
FIVE_KEY = pygame.K_5
SIX_KEY = pygame.K_6
SEVEN_KEY = pygame.K_7
EIGHT_KEY = pygame.K_8
NINE_KEY = pygame.K_9